// Copyright (C) 2016  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 196 10/24/2016)
// Created on Tue Jan 10 22:09:27 2017

LogicAnalyzer LogicAnalyzer_inst
(
	.inclk0_10MHz(inclk0_10MHz_sig) ,	// input  inclk0_10MHz_sig
	.rst(rst_sig) ,	// input  rst_sig
	.dataIn(dataIn_sig) ,	// input [2:0] dataIn_sig
	.TxD(TxD_sig) ,	// output  TxD_sig
	.pll_output_debug(pll_output_debug_sig) ,	// output  pll_output_debug_sig
	.clk_div16_debug(clk_div16_debug_sig) ,	// output  clk_div16_debug_sig
	.dataOut_debug(dataOut_debug_sig) ,	// output [7:0] dataOut_debug_sig
	.state_debug(state_debug_sig) 	// output [4:0] state_debug_sig
);

